### ISSUE TITLE
Image url 404 when remote CSS base url are not same with web page host url.

### ISSUE THREAD

**Issue by andycall** [openwebf/webf#281]
### Affected version

main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

If a web page is hosting at `http://example.com`:

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="http://cdn.example.com/static/a.css">
  </head>
  <body>
    <div class="container">helloworld</div>
  </body>
</html>
```

And the `a.css` load a background image by relative path.

```css
.container {
  width: 100px;
  height: 100px;
  background: url(./background.png) no-repeat;
}
```

WebF will request `http://example.com/background.png` for image, but Chrome will request `http://cdn.example.com/static/background.png` for image.

### Code example

-

### Expected results

WebF will request `http://cdn.example.com/static/background.png` for image just like Chrome do.

### Actual results

Request `http://example.com/background.png` for image
